<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="1" failures="1" errors="0" time="0.022549448">
    <testsuite name="src/components/__tests__/PasswordInput.test.jsx" timestamp="2025-07-16T21:20:31.541Z" hostname="tony" tests="1" failures="1" errors="0" skipped="0" time="0.022549448">
        <testcase classname="src/components/__tests__/PasswordInput.test.jsx" name="calls handleChange on input change" time="0.021679454">
            <failure message="expected &quot;log&quot; to be called with arguments: [ &apos;Entering password...&apos; ][90m

Number of calls: [1m0[22m
[39m" type="AssertionError">
AssertionError: expected &quot;log&quot; to be called with arguments: [ &apos;Entering password...&apos; ]

Number of calls: 0

 ‚ùØ src/components/__tests__/PasswordInput.test.jsx:24:18
            </failure>
        </testcase>
    </testsuite>
</testsuites>
